- name: "add vscode repo"
  become: true
  deb822_repository:
    name: vscode
    types: deb
    uris: https://packages.microsoft.com/repos/code
    suites: stable
    components: main
    signed_by: https://packages.microsoft.com/keys/microsoft.asc

- name: "install vscode"
  become: true
  apt:
    name:
      - code
    state: latest
    update_cache: yes
