tls:
  options:
    default:
      sniStrict: true
  stores:
    default: {}
  certificates:
    - certFile: /certs/live/idm.spatz.wtf/fullchain.pem
      keyFile: /certs/live/idm.spatz.wtf/privkey.pem
    - certFile: /certs/live/spatz.wtf/fullchain.pem
      keyFile: /certs/live/spatz.wtf/privkey.pem
    - certFile: /certs/live/vpn.spatz.wtf/fullchain.pem
      keyFile: /certs/live/vpn.spatz.wtf/privkey.pem
