- name: "install nfs client"
  become: true
  apt:
    name: nfs-common

- name: "create mount points"
  become: true
  file: path={{ item }} state=directory
  with_items:
    - /u
    - /opt/skel
    - /opt/aufnahmen
    - /opt/sim_tracks

- name: "copy script"
  become: true
  copy:
    src: "wait-for-nfs.sh"
    dest: /etc/systemd/system/wait-for-nfs.sh
    owner: root
    group: root
    mode: 0755
  register: copy

- name: template mounts and service
  become: true
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: '0644'
  with_items:
    - opt-aufnahmen.mount
    - opt-sim_tracks.mount
    - opt-training_data.mount
    - opt-skel.mount
    - u.mount
    - wait-for-nfs@.service
  register: template

- name: "daemon reload"
  become: true
  shell: systemctl daemon-reload
  when: copy.changed or template.changed or force_all

- name: "enable / reload mounts"
  become: true
  systemd_service:
    daemon_reload: true
    name: "{{ item }}"
    enabled: true
    state: restarted
  with_items:
    - opt-aufnahmen.mount
    - opt-sim_tracks.mount
    - opt-skel.mount
    - u.mount
  when: copy.changed or template.changed or force_all
