- name: "install nfs client"
  become: true
  apt:
    name: nfs-common

- name: "create mount points"
  become: true
  file: path={{ item }} state=directory
  with_items:
    - /u
    - /opt/skel
    - /opt/aufnahmen
    - /opt/sim_tracks

- name: "NFS homes at /u"
  become: true
  lineinfile:
    path: /etc/fstab
    regexp: '^(eric|sven|pc00).spatz.(wtf|vpn):/(home|mnt/user\-home) '
    line: "{{ mount_hostname }}:/mnt/user-home /u nfs auto,fsc,{{ mount_extra_args }} 0 0"
  register: homes

- name: "NFS skel at /opt/skel"
  become: true
  lineinfile:
    path: /etc/fstab
    regexp: "^(sven|pc00).spatz.(wtf|vpn):/mnt/auxiliary/skel "
    line: "{{ mount_hostname }}:/mnt/auxiliary/skel /opt/skel nfs ro,hard,intr,fsc,auto,{{ mount_extra_args }} 0 0"
  register: skel

- name: "NFS aufnahmen at /opt/aufnahmen"
  become: true
  lineinfile:
    path: /etc/fstab
    regexp: "^(eric|sven|pc00).spatz.(wtf|vpn):/(opt|mnt)/aufnahmen "
    line: "{{ mount_hostname }}:/mnt/aufnahmen /opt/aufnahmen nfs ro,hard,intr,fsc,auto,{{ mount_extra_args }} 0 0"
  register: aufnahmen

- name: "NFS sim_tracks at /opt/sim_tracks"
  become: true
  lineinfile:
    path: /etc/fstab
    regexp: "^(sven|pc00).spatz.(wtf|vpn):/mnt/auxiliary/sim_tracks "
    line: "{{ mount_hostname }}:/mnt/auxiliary/sim_tracks /opt/sim_tracks nfs auto,fsc,{{ mount_extra_args }} 0 0"
  register: sim_tracks

- name: "remove old and failed spatz mount hacky hack"
  become: true
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: "{{ item }}"
  with_items:
    - "^/ /mnt/localroot "
    - "^/mnt/localroot/home/spatz "
  register: old

- name: "daemon reload"
  become: true
  shell: systemctl daemon-reload
  when: homes.changed or skel.changed or aufnahmen.changed or sim_tracks.changed or old.changed

- name: "mount all"
  become: true
  command: /bin/mount -a
  when: homes.changed or skel.changed or aufnahmen.changed or sim_tracks.changed or old.changed
