- name: Common
  hosts:
    - clients
  tags:
    - pc
    - ci
  roles:
    - update
    - essential-tools
    - docker
    - ansible-user
    - spatz-user
    - netbird
    - ufw

- name: PCs
  hosts:
    - pc
  tags:
    - pc
    - pc_werkstatt
  roles:
    - remove-legacy-stuff
    - kanidm
    - mounts
    - kill-snap-get-flatpak
    - desktop-programs
    - shells
    - nvidia
    - nvidia-docker
    - vnc-client
    - ade
    - sudo
    - vscode

- name: Teamraum Audio
  hosts: teamraum
  tags: pc
  roles:
    - pulseaudio

- name: CI
  hosts: ci
  tags:
    - ci
  roles:
    - gitlab-runner

- name: GPU
  hosts: gpu
  tags:
    - gpu
  roles:
    - nvidia
    - nvidia-docker
