- name: Common
  hosts:
    - clients
  roles:
    - update
    - essential-tools
    - docker
    - ansible-user
    - spatz-user
    - netbird
    - ufw

- name: PCs
  hosts:
    - pc
  roles:
    - remove-legacy-stuff
    - kanidm
    - mounts
    - kill-snap-get-flatpak
    - desktop-programs
    - shells
    - vnc-client
    - ade
    - sudo
    - vscode
    - vnc-server
    - virtualgl

- name: Teamraum Audio
  hosts: teamraum
  roles:
    - pulseaudio

- name: CI
  hosts: ci
  roles:
    - gitlab-runner

- name: GPU
  hosts: gpu
  roles:
    - nvidia
    - nvidia-docker

- name: NUC
  hosts: nuc
  roles:
    - kill-snap-get-flatpak
    - shells
    - vnc-client
    - ade
    - sudo
    - vnc-server
    - virtualgl
    - spatz-background
    - coral
    - spatz-setup