- name: PCs
  hosts: pc
  roles:
    - remove-legacy-stuff
    - update
    - essential-tools
    - kanidm
    - docker
    - ansible-user
    - spatz-user
    - mounts
    - kill-snap-get-flatpak
    - desktop-programs
    - shells
    - pulseaudio
