- name: "install udev rule for flir"
  become: true
  lineinfile:
    path: /etc/udev/rules.d/40-flir-spinnaker.rules
    create: yes
    line: "SUBSYSTEM==\"usb\", ATTRS{idVendor}==\"1e10\", GROUP=\"spatz\", MODE=\"0666\""
    regexp: 'ATTRS{idVendor}==\"1e10\"'

- name: "copy usb-flir systemd unit"
  become: true
  copy:
    src: usb-flir.service
    dest: /etc/systemd/system/usb-flir.service

- name: "configure usb-flir systemd unit"
  become: true
  systemd:
    name: "usb-flir.service"
    state: started
    daemon_reload: true
    enabled: true