- name: "add kanidm repo"
  become: true
  deb822_repository:
    name: kanidm
    types: deb
    architectures: amd64
    uris: https://kanidm.github.io/kanidm_ppa
    suites: "{{ ansible_distribution_release }}"
    components: stable
    signed_by: https://kanidm.github.io/kanidm_ppa/kanidm_ppa.asc

- name: "install"
  become: true
  apt:
    name:
      - kanidm
    state: latest
    update_cache: yes
