- name: Common
  hosts: server
  roles:
    - update
    - essential-tools
    - admin-user
    - sudo
    - authorized-keys
    - docker
    - netbird

- name: Infra
  hosts: sven
  roles:
    - nfs-server
    - compose-sven
    - pulseaudio
    - kanidm-client
    - ufw
    - bacula
    - gasket-build

- name: GitLab
  hosts: garry
  roles:
    - compose-garry
