- name: Infra
  hosts: server
  roles:
    - update
    - essential-tools
    - nfs-server
    - docker
    - sven-compose
    - pulseaudio
    - kanidm-client
    - dominion_solutions.netbird.netbird
    - ufw
