- name: Install common packages
  become: true
  apt:
    state: present
    update_cache: true
    name:
      - libuser
      - graphviz
      - tmux
      - figlet
      - gimp
      - aria2
      - python3
      - python3-pip
      - arandr
      - thunar-archive-plugin
      - make
      - ninja-build
      - git
      - mcrypt
      - meld
      - x11vnc
      - htop
      - btop
      - iftop
      - neovim
      - ncdu
      - xdotool
      - glade
      - gparted
      - tree
      - libperl-dev
      - clinfo
      - parallel
      - curl
      - bat
      - speedtest-cli
      - vlc
      - neofetch
      - net-tools
      - mesa-utils
      - pdftk
