- name: "add mozilla repo"
  become: true
  deb822_repository:
    name: mozilla
    types: deb
    uris: https://packages.mozilla.org/apt
    suites: mozilla
    components: main
    signed_by: https://packages.mozilla.org/apt/repo-signing-key.gpg

- name: "pin mozilla ppa"
  become: true
  copy:
    src: mozillappa.pref
    dest: /etc/apt/preferences.d/mozillappa.pref
    owner: root
    group: root
    mode: 0644

- name: Install common packages
  become: true
  apt:
    state: present
    update_cache: true
    name:
      - cmake
      - libuser
      - graphviz
      - tmux
      - figlet
      - gimp
      - aria2
      - python3
      - python3-pip
      - python3-venv
      - arandr
      - thunar-archive-plugin
      - make
      - ninja-build
      - git
      - git-lfs
      - mcrypt
      - meld
      - x11vnc
      - htop
      - btop
      - iftop
      - neovim
      - ncdu
      - xdotool
      - glade
      - gparted
      - tree
      - libperl-dev
      - clinfo
      - parallel
      - curl
      - bat
      - speedtest-cli
      - vlc
      - neofetch
      - net-tools
      - mesa-utils
      - pdftk
      - firefox
      - ansible
      - libfuse2 # for AppImage
