- name: "remove legacy packages"
  become: true
  apt:
    name:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent

- name: "install prerequisites via apt"
  become: true
  apt:
    name:
      - ca-certificates
      - curl
    state: latest
    update_cache: yes

- name: "add docker repo"
  become: true
  deb822_repository:
    name: docker
    types: deb
    architectures: amd64
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components: stable
    signed_by: https://download.docker.com/linux/ubuntu/gpg

- name: "install and update"
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: "add docker group to ansible user"
  become: true
  user:
    name: ansible
    append: true
    groups: docker

- name: "add docker group to djtrumpadmin user"
  become: true
  user:
    name: djtrumpadmin
    append: true
    groups: docker

- name: "copy daemon config with log-rotation"
  become: true
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  register: config

- name: "restart docker daemon"
  become: true
  shell: systemctl restart docker
  when: config.changed or force_all