all:
  vars:
    ansible_user: ansible
    ansible_ssh_port: 2244
    ansible_ssh_private_key_file: ../ansible_key
    netbird_register: true
    netbird_mgmt_url: https://vpn.spatz.wtf
    netbird_setup_key: "{{ lookup('file', '../netbird_setup.key') }}"
    force_all: false # if true => must be run as local spatz user! requires all other users being logged out!

global_ip:
  vars:
    host_domain: spatz.wtf
    ansible_host: "{{inventory_hostname}}.{{host_domain}}"  
    mount_hostname: "sven.{{host_domain}}"
    mount_via_netbird: false

static_ip:
  hosts:
    pc01:
      static_ip: 221
    pc02:
      static_ip: 222    
    pc03:
      static_ip: 223
    pc04:
      static_ip: 224
    pc05:
      static_ip: 225
    pc06:
      static_ip: 226    
    pc07:
      static_ip: 227
    pc08:
      static_ip: 228
    pc09:
      static_ip: 229

netbird:
  vars:
    host_domain: spatz.vpn
    ansible_host: "{{inventory_hostname}}.{{host_domain}}"  
    mount_hostname: "pc00.{{host_domain}}"
    mount_via_netbird: true

spatz:
  vars:
    vnc_autostart: true