- name: "copy to ansible user home"
  copy:
    src: gitlab-runner
    dest: /home/ansible
    owner: ansible
    group: ansible
  register: copy

- name: "template template.toml"
  template:
    src: "template.toml.j2"
    dest: /home/ansible/template.toml
    owner: ansible
    group: ansible

- name: "remove runner config"
  ansible.builtin.file:
    path: /home/ansible/gitlab-runner/runner_data/config.toml
    state: absent
  when: copy.changed or force_all

- name: "docker compose up"
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/ansible/gitlab-runner
    remove_orphans: true
  when: copy.changed or force_all

- name: "register runner"
  become: true
  shell:
    executable: /bin/bash
    chdir: /home/ansible/gitlab-runner
    cmd: |
      source .env
      docker exec gitlab-runner gitlab-runner register \
        --non-interactive \
        --template-config /template.toml \
        --url "https://git.spatz.wtf/" \
        --token "$RUNNER_TOKEN_{{ inventory_hostname }}" \
        --executor "docker" \
        --docker-image "alpine:latest" \
        --docker-privileged \
        --docker-volumes "/certs/client"
  when: copy.changed or force_all
