- name: "copy to ansible user home"
  copy:
    src: sven
    dest: /home/ansible
    owner: ansible
    group: ansible
  register: copy

- name: "docker compose up"
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/ansible/sven
    remove_orphans: true
  when: copy.changed
