- name: "remove legacy packages"
  become: true
  apt:
    name:
      - docker.io
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent

- name: "remove legacy apt key"
  become: true
  apt_key:
    keyring: /etc/apt/trusted.gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: absent

- name: "remove legacy apt repo"
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: absent

- name: "add docker repo"
  become: true
  deb822_repository:
    name: docker
    types: deb
    architectures: amd64
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components: stable
    signed_by: https://download.docker.com/linux/ubuntu/gpg

- name: "install and update"
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: "ensure local group docker exists"
  become: true
  group:
    name: docker
    local: true
    gid: 800
    state: present

- name: "add spatz to docker group"
  become: true
  user:
    name: spatz
    groups: docker
    append: yes