- name: "install nfs-kernel-server"
  become: true
  apt:
    name:
      - nfs-kernel-server
    state: latest
    update_cache: yes

- name: "enable rpcbind nfs-kernel-server"
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - rpcbind
    - nfs-kernel-server

- name: "generate exports definition"
  become: true
  vars:
    export_args: "no_root_squash,rw,nohide,insecure,no_subtree_check,async,crossmnt"
    exports:
      - /mnt/user-home
      - /mnt/auxiliary/skel
      - /mnt/auxiliary/sim_tracks
      - /mnt/aufnahmen
    common_hosts:
      - 134.60.25.0/24
      - 134.60.113.31
      - 134.60.113.50
    additional_aufnahmen_hosts:
      - 134.60.113.17
      - 134.60.113.18
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  register: generate

- name: "copy config"
  become: true
  copy:
    src: nfs.conf
    dest: /etc/nfs.conf.d/nfs.conf
    owner: root
    group: root
    mode: 0644
  register: config

- name: "reload NFS & exportfs"
  become: true
  shell: systemctl reload nfs-kernel-server && exportfs -a
  when: generate.changed or config.changed
