- name: "nfs-server: install nfs-kernel-server"
  become: true
  apt:
    name:
      - nfs-kernel-server
    state: latest
    update_cache: yes

- name: "nfs-server: enable rpcbind nfs-kernel-server"
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - rpcbind
    - nfs-kernel-server

- name: "nfs-server: copy exports definition"
  become: true
  copy:
    src: sven/nfs-exports
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  register: copy

- name: "nfs-server: reload NFS & exportfs"
  become: true
  shell: systemctl reload nfs-kernel-server && exportfs -a
  when: copy.changed
