- name: "copy to ansible user home"
  copy:
    src: garry
    dest: /home/ansible
    owner: ansible
    group: ansible
  register: copy

- name: gitlab-data directories
  become: true
  file:
    path: /mnt/gitlab-data/{{ item }}
    state: directory
  with_items:
    - config
    - logs
    - data

- name: "copy gitlab config"
  become: true
  copy:
    src: config
    dest: /mnt/gitlab-data/
    owner: root
    group: root
  register: copy

- name: gitlab keys permissions
  become: true
  file:
    path: /mnt/gitlab-data/config/{{ item }}
    mode: 0600
  with_items:
    - ssh_host_ecdsa_key
    - ssh_host_ed25519_key
    - ssh_host_rsa_key

- name: "docker compose up"
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/ansible/garry
    remove_orphans: true
  when: copy.changed or force_all

- name: crontab timezone UTC
  ansible.builtin.cron:
    name: CRON_TZ
    env: yes
    value: UTC

- name: "backup cron"
  become: true
  cron:
    name: "gitlab-backup"
    minute: "0"
    hour: "1"
    job: "docker exec gitlab /opt/gitlab/bin/gitlab-backup create CRON=1 SKIP=registry,artifacts && curl -fsS -m 10 --retry 5 -o /dev/null {{ lookup('file', 'gitlab-backup.healthcheck-url') }}"
