- name: "copy to ansible user home"
  copy:
    src: garry
    dest: /home/ansible
    owner: ansible
    group: ansible
  register: copy

- name: "docker compose up"
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/ansible/garry
    remove_orphans: true
  when: copy.changed or force_all

- name: "backup cron"
  become: true
  cron:
    name: "gitlab-backup"
    minute: "0"
    hour: "1"
    job: "docker exec gitlab /opt/gitlab/bin/gitlab-backup create CRON=1 SKIP=registry,artifacts && curl -fsS -m 10 --retry 5 -o /dev/null {{ lookup('file', 'gitlab-backup.healthcheck-url') }}"
