- name: "sven-compose: copy to ansible user home"
  ansible.builtin.copy:
    src: sven
    dest: /home/ansible
    owner: ansible
    group: ansible
  register: copy

- name: "sven-compose: docker compose up"
  community.docker.docker_compose_v2:
    project_src: /home/ansible/sven
    remove_orphans: true
  when: copy.changed
